let valeur=prompt("Veuillez entrer une valeur:");
 let n=Number(prompt("Entrez un nombre :"));
 prompt();
 let x = "150";
 let y = 150 ;
 let z = true ;
 console.log(typeof x);
  console.log(typeof y);
   console.log(typeof z);
   x = Number(x);
   console.log(typeof x);